### PR TITLE
Add build instructions

### PR DESCRIPTION
**Pull request by fleutot**
Remove Makefile, since it refers to other Makefiles that do not exist (old
file?).

### CODE REVIEW

**Comment by FormerLurker** [comment]
Is there any reason the existing cmake won't work for you?  Asking because that's already there and is working.  The existing make should have been deleted, so good catch.

**Comment by fleutot** [comment]
@FormerLurker I might have missed the intended way of building (hence the need for update of the readme ;) ). The way I've seen and used cmake before is as described in my addition to the readme file, but it's been a while.

I'm not sure what you mean by "the existing cmake"? What is your intended way of building?

**Comment by fleutot** [comment]
I understand the confusion. Github has a weird way to deal with single commit pull requests: first line of the commit message in title, and the rest of the commit message as the first post in conversation? That really doesn't look like a PR, just a discussion. And I shall thank YOU for this code, very cool!

**Comment by FormerLurker** [comment]
Can you retarget the devel branch (not rc/devel) and push to your repo?  Be sure to do a fetch and pull from the upstream branch first.  Then I'll add this.

Alternatively I could just update the readme.md manually and delete the old make file if it's too much of a bother.  Let me know :)

**Comment by fleutot** [comment]
Do you mean that you want the Pull Request to target branch devel?
Do you want me to rebase this branch on top of your current devel?

**Comment by fleutot** [comment]
I did what I supposed you were aiming for: my branch now based on your most recent devel, and its PR targeting back to devel. (I think it's weird that github calls it "base branch". What it's doing is pointing out what it's going to merge **into**. Not branch **from**. Not always the same.)

**Comment by FormerLurker** [comment]
That's exactly what I wanted, thank you!  You will see this on the master readme once this build is promoted.  I've been doing a lot of work on it recently.

**Pull request merged**
