### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by wolfmanjm**
Fix typo so it builds on Linux (which is case sensitive)

### CODE REVIEW

**Comment by FormerLurker** [comment]
I think another issue is that there should be no makefile since I switched to cmake!  Check the actions and see if the linux build there works for you.

**Comment by wolfmanjm** [comment]
Ahh ok, I was building the command line version as I don't use octoprint, and the command line version would work well in my host called smoopi which is a smoothie specific rpi touchscreen based host. So I have no access to actions (which I presume is a ocoprint thing?)

**Comment by FormerLurker** [comment]
I mean github actions:  https://github.com/FormerLurker/ArcWelderLib/actions/runs/327928389

I'm using cmake to generate artifacts there.  You should be able to get it working with cmake too.  Let me know if it works for you and I'll just delete that makefile which is confusing things!  I'm glad you brought it to my attention.

**Comment by wolfmanjm** [comment]
Ahh... will do, I'm not much of a cmake user :) but I'll give it a go, I was able to build the console on linux using make and hand building the console app. I'll try the github thingy. Thanks looks very interesting as Smoothie has had G2/G3 since its inception and I just fixed G2/G3 for 3d printers.

**Comment by FormerLurker** [comment]
> I'm not much of a cmake user :) but I'll give it a go
If you get it working, please let me know what you did and I'll post a doc.  Going to start making a wiki, and things like this are essential.  I don't yet have a working mac version, so if you know anything about that, I'd love to hear it.  I don't have access to a mac.

>  I just fixed G2/G3 for 3d printers
That is AWESOME!  Can you send me the M115 response for Smoothie for the version where you fixed arcs?  I am adding firmware issue detection to the Octoprint plugin, and I need lots of examples in order to make it work.  If I know the M115 format, how to detect smoothieware, and what the minimum version with arc support for 3d printers, I can get it working in there too.  Currently I have Marlin, Klipper, Prusa Firmware and Prusa Buddy firmware examples.  I still have a lot to fill in though...

**Comment by wolfmanjm** [comment]
Ok seems it needs a minimum of  CMake version 3.13 or higher, but Ubuntu 18.04.5 LTS has cmake version 3.10.2, so no go on getting CMake to work. (Upgrading would be a big pain but I'll look into it when I have somne spare time).

However make works fine for the ArcWelder, TCLAP, GcodeProcessorLib directories and I used the following command line to build the command line version:
``g++ -I ../ArcWelder -I ../GcodeProcessorLib -I ../TCLAP ArcWelderConsole.cpp ../GcodeProcessorLib/*.o ../ArcWelder/*.o``

I'll do a separate issue with M115 for Smoothie, unfortunately I use git hashes as the version so they are not monotonic, but I can add a string to indicate if G2/G3 is supported, or if you have a better idea let me know.

**Comment by FormerLurker** [comment]
You could add extended capability reporting for M115.  Every line starts with ```Cap:```, and each cap row is sent as a separate line.  Here is an example of each line from marlin:

```
FIRMWARE_NAME:Marlin 2.0.7.2 (Oct 31 2020 14:58:34) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff,
Cap:SERIAL_XON_XOFF:0,
Cap:BINARY_FILE_TRANSFER:0,
Cap:EEPROM:1,
Cap:VOLUMETRIC:1,
Cap:AUTOREPORT_TEMP:1,
Cap:PROGRESS:0,
Cap:PRINT_JOB:1,
Cap:AUTOLEVEL:1,
Cap:RUNOUT:0,
Cap:Z_PROBE:1,
Cap:LEVELING_DATA:1,
Cap:BUILD_PERCENT:1,
Cap:SOFTWARE_POWER:0,
Cap:TOGGLE_LIGHTS:0,
Cap:CASE_LIGHT_BRIGHTNESS:0,
Cap:EMERGENCY_PARSER:1,
Cap:PROMPT_SUPPORT:0,
Cap:SDCARD:1,
Cap:AUTOREPORT_SD_STATUS:0,
Cap:LONG_FILENAME:1,
Cap:THERMAL_PROTECTION:1,
Cap:MOTION_MODES:0,
Cap:ARCS:1,
Cap:BABYSTEPPING:1,
Cap:CHAMBER_TEMPERATURE:0
```

If ARCS is in there, and is set to 1 (true) my detection algorithm will pick it up.

> unfortunately I use git hashes as the version

That is most unfortunate.  You could start to use git releases to tag the version.  I use the format: x.x.x[+{commits_ahead}-{git_hash}]. (stuff in the brackets is only added if the commit has no tag).  It's incredibly useful.  You could then add a  FIRMWARE_VERSION tag to M115:

```FIRMWARE_VERSION:v0.8.0+700-ge4f3f60e```

Are you the smoothieware creator?  awesome :)  Nice to meet you!

**Comment by wolfmanjm** [comment]
Smoothie currently does...

`FIRMWARE_NAME:Smoothieware, FIRMWARE_URL:http%3A//smoothieware.org, X-SOURCE_CODE_URL:https://github.com/Smoothieware/Smoothieware, FIRMWARE_VERSION:edge-2a68f14, X-FIRMWARE_BUILD_DATE:Oct 23 2020 10:57:53, X-SYSTEM_CLOCK:120MHz, X-AXES:5, X-GRBL_MODE:0, X-CNC:0, X-MSD:1`

Typical Marlin uses non-standard formats ;) According to reprap gcode standard, capabilities should be X-xxxx which is what we use. I could easily add X-ARCS:1

If you like that I'll add it ASAP.

I'm not Smoothies creator (that would be Arthur Wolf) but I am currently the primary developer/maintainer :) (also for SmoothieV2)

I'll look into git releases, but typically we do not use releases as we upload the binaries to github as needed. And I didn't do a monotonic release number because it is really hard to maintain automatically, and sometimes we do new binaries very frequently, I push them as firmware-latest.bin to the Firmware directory, for people to test before it becomes a release.

**Comment by FormerLurker** [comment]
> Typical Marlin uses non-standard formats ;) According to reprap gcode standard, capabilities should be X-xxxx which is what we use. I could easily add X-ARCS:1

Ug..  Well, I'll add the standard method in addition to the current non-standard method :)  I'm glad you let me know.  I'm learning this stuff as I go, so thank you for the education!

> X-ARCS:1

That would be excellent.  I'm unsure of exactly how arcs are processed in smoothie.  I'm guessing there is some kind of interpolation.  Some way to discover those settings would also be fantastic.  I'm working to add a few new commands to Marlin (including [prusa's forks](https://github.com/prusa3d/Prusa-Firmware/pull/2657) and klipper eventually too.  It's still in flux ATM, but the new proposed M214 and updated M503 (not sure how that works in your firmware) will make it a lot easier to deal with arc config and discovery.

> I'll look into git releases, but typically we do not use releases as we upload the binaries to github as needed.

Understood.  Switching methods is always difficult too.  If it ain't broke...

> because it is really hard to maintain automatically

You might want to look at how Klipper does it.  I haven't examined it in detail (just enough to figure out how the numbers are constructed), but it seems to use github tags + commits ahead + hash.

> I'm not Smoothies creator (that would be Arthur Wolf) but I am currently the primary developer/maintainer :) (also for SmoothieV2)

I need to meet more folks in the 3d printing world.  Thank you for the info, and thank YOU for supporting the open source community!  Feel free to message/email any time you wish.  I'm also on discord at  FormerLurker#5525 if you use that.

**Comment by wolfmanjm** [comment]
BTW congratulations on this code, it is a very clever bit of S/W, and sorely needed until slicers can do it themselves. I notice that Fusion360 just added the capability to output G2/G3 on its 3d gcode output, which is why I fixed the G2/G3 for 3d printers, we always had G2/G3 for CNC but only for XYZ axis. I added the E interpolation very recently.

**Comment by FormerLurker** [comment]
> BTW congratulations on this code, it is a very clever bit of S/W

Awww.. thanks!  The idea is pretty straightforward.  I'm frankly surprised it hasn't been done before.

> I added the E interpolation very recently.

It would also be excellent if a Z parameter could be added.  I've been wanting to update this to work in spiral vase mode, but the capability isn't there as far as I know to draw an arc with a different start/end z coordinate.  Maybe I'll submit a feature request.

**Comment by wolfmanjm** [comment]
Yea I tend to try to not invent new stuff if there is already a documented way to do it. Unfortunately the other firmware developers like to invent new gcodes when there is a perfectly good one available, makes compatiblitly hard.

BTW the reference I made earlier was to this...  https://reprap.org/wiki/G-code#M115:_Get_Firmware_Version_and_Capabilities seems like DC42 also added his own format as well. Also smoothie does support M115 so that is not fully up to date. The X- stuff was documented somewhere else though and seems someone deleted it.

**Comment by wolfmanjm** [comment]
Smoothie does support Z as that is standard in CNC to do spiral paths. see http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g2-g3. We try to follow the NIST standard of G-Code.

So basically Z will be linearly interpolated if given (same as E or ABC).

**Comment by wolfmanjm** [comment]
ok smoothie will now output this when given M115...

`FIRMWARE_NAME:Smoothieware, FIRMWARE_URL:http%3A//smoothieware.org, X-SOURCE_CODE_URL:https://github.com/Smoothieware/Smoothieware, FIRMWARE_VERSION:edge-9348830, X-FIRMWARE_BUILD_DATE:Nov  3 2020 21:04:30, X-SYSTEM_CLOCK:120MHz, X-AXES:5, X-GRBL_MODE:0, X-ARCS:1, X-CNC:0, X-MSD:1`

If it isn't there then it is an older version which does support G2/G3 but not for 3d printers with extruders.

**Comment by FormerLurker** [comment]
Thank you!  I will make sure folks running Smoothie with arc support enabled will see that in the next version of the arc welder plugin!

**Comment by wolfmanjm** [comment]
If you want to try the G2 with Z feature, I'll see if I can get arthur to send you a smoothieboard to test with. I'm not sure he has any in stock but I can ask :) Printing a spiral using G2/G3 would be awesome :) of course calculating the E will be tricky.

**Comment by wolfmanjm** [comment]
BTW I initially tested this on some CNC gcode I had which is a programmatically generated spiral...  https://gist.github.com/wolfmanjm/64038a4d1bc7295994ee532ea2429101 however for some reason it did not find any arcs, I am not sure why as it should be all arcs. Does your gcode parser require Z or E or some other well known pattern?

**Comment by FormerLurker** [comment]
It requires E.  I could make it work for travel easily, but it's not set up for that ATM since I've never seen any travel that moves in an arc yet.

In arc_welder.cpp on line 376 there is a check to make sure the current and previous command are either extrusion or retractions.  Some additional changes will be needed, including the ability to output a G2/G3 without an E parameter.  Mostly trivial stuff.  I'll look into that.

Are travel curves something you've seen?  I'm guessing it would be common for CNC.

**Comment by wolfmanjm** [comment]
No travel curves never happen, they are always cutting curves G2/G3 is always like G1. However the initial position to the start of the arc would likely be a G0.
I think this would be useful for laser cutters too, and they are more likely to be like CNC with G0 and G1, G0 moves for a laser are always with laser off and G1/2/3 are always with laser on.
However I was just using my spiral g code as a test, I can easily hack it to use only G1 and to insert an E.
Remember that slicers can use G10/G11 for H/W retraction instead of using a G1 with a negative E. However I ran your program on some gcode I use for my delta which uses G10/G11 for retraction (and I use volumetric E) and it all seems to work well. I'll try and actualy print it and make sure the extrusion looks good. - Thanks

**Comment by FormerLurker** [comment]
> However I ran your program on some gcode I use for my delta which uses G10/G11 for retraction (and I use volumetric E) and it all seems to work well. I'll try and actually print it and make sure the extrusion looks good. - Thanks

NP.  G10/G11 are..  a bit messed up ATM.  The way they are typically used it should still be OK (retract, move, deretract).  It looks like I started with G10, but when I looked at the G11 code I found this:

```
void gcode_position::process_g11(position* pos, parsed_command& cmd)
{
	// Todo: Fix G11
}
```
Whoops..  Will try to get that working too.

**Comment by wolfmanjm** [comment]
I updated my goto spiral generator to include E. It works great converts most of the segments to arcs, except the first few becuase the resolution is too small, (0.001mm) even with -r=0.001 it still missed the first few, if I did -r=0.0001 it didn't convert any of them. Only minor glitches though :)

Here is my test input file https://gist.github.com/7e319d96f0584fce1660581738d732dc

**Comment by FormerLurker** [comment]
Since Arc Welder is geared towards 3d printers, it only outputs 3 decimal places for X and Y, but I could have it examine the precision of the incoming gcodes and adapt to that.  However, that doesn't explain why the first bit of the spiral isn't converted.  I'll look into the inner part of the spiral to see what's up.

Regarding the -r parameter, that probably means something a bit different than you are thinking.  If you measure a part printed with arc welder, it will deviate by, at most, the value you supply for r.  The path of any individual arc may deviate at most +- 1/2 that value when compared to the original segment path.  I have an illustration of this [here](https://plugins.octoprint.org/assets/img/plugins/arc_welder/arc_creation_example.png).

**Comment by wolfmanjm** [comment]
oh yea I forgot about -r  I did read it, then for some reason I presumed it was a precision thing :)

I would think higher precision capability is a good thing, some slicers do output absolutely tiny segments even if they cannot be printed at that resolution (S3D is one for instance).

This spiral file is my goto test for streaming becuase on nearly all systems I test it on the intial inner spirals are really jerky as the printer finishes the segments before the host can fill up the look ahead buffer. Converting it to G2/G3 would probably fix that. (Also playing from SD card also fixes it).

If you are curious how Smoothie handles G2/G3 and what parameters we use you can look here.... https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/robot/Robot.cpp#L1545
We have an arc_error term which determines how fine the segments are. It varies based on the size of the arc.
The original arc code was based on the original GRBL code, but has since been upgraded by an expert in arc math :) (He added the arc error instead of the arc_segment length).

**Comment by FormerLurker** [comment]
Thanks for the info!  I will dig into the code.  Also, I will consider your offer for a test board (thank you for suggesting it).  I need a printer I can connect it to :)  I've not got much experience with that sort of thing, but I'm a quick learner.

Regarding the spiral, check out segmented_shape.h and find CIRCLE_GENERATION_A_ZERO_TOLERANCE.  As you can see I am still deciding what to do with this.  It is used in segmented_shape.cpp in the ```try_create_circle``` function, which creates a circle that runs through all three provided points.  A is calculated and checked like so:

```
double a = x1 * (y2 - y3) - y1 * (x2 - x3) + x2 * y3 - x3 * y2;

if (utilities::is_zero(a, CIRCLE_GENERATION_A_ZERO_TOLERANCE))
{
     return false;
}
```
and later is used to determine X and Y center of the circle:
```
double x = -b / (2.0 * a);
double y = -c / (2.0 * a);
```
If A is too small, bad things happen (overflows).  Later when I'm calculating the direction of rotation (CW/CCW) it's possible to compute the wrong direction, which is really bad.  I've been planning to work out exactly what is going on here, but it is tricky business.  I did some trial and error and determined that errors can happen if the value of A is between 0.000001 and 0.0000001.  To be conservative, I multiplied the upper end by 10 and used that (don't want any arcs moving in the wrong direction!!)  If you change the define to this:

```#define CIRCLE_GENERATION_A_ZERO_TOLERANCE 0.000001```

This is what your spiral will look like:

image

Looks like I need to spend a weekend on these three problems:

* Implement and test G10/G11
* Add variable precision output based on the input gcode
* Figure out how to handle small values for A in the try_create_circle function, or maybe figure out something entirely different.

**Comment by FormerLurker** [comment]
[Here](https://gist.github.com/FormerLurker/84157a7cf277c5f4f5f2d20c1dd8e79e) is a gist containing the converted code.  It only has one G1, the starting point.

**Comment by wolfmanjm** [comment]
Wow that is amazing, 100% conversion! That is sort of what I thought it should have done. I understand your pain about circles going in the wrong direction, I ran into a similar problem doing my gcode viewer code for smoopi. I forget exactly what the issue was, but I ended up mostly copying the code from bCNC where he seemed to have avoided the problem (in the viewer).

**Comment by wolfmanjm** [comment]
FYI the problem with you handling G10/G11 is that becuase it is firmware retraction you don't know how much it is retracting by as that is set in the firmware (usually by M207 and M208 and saved with M500) you can probably find the values with M503.

However I am not entirely sure you need to know how much it is retracting by as G11 "usually" leaves it where it was, but there is a setting that can either stop short of where it was or go a little beyond where it was.
In reality I suspect there will never be an arc anywhere near a G10/G11 as that is usually done on a layer change (but not always).

**Comment by wolfmanjm** [comment]
Can you email me your address? Chris Cecil (the H/W tech for smoothieboard) will send you a smoothieboard.
My email is morris@wolfman.com
All things smoothie are in the wiki http://smoothieware.org/

**Comment by wolfmanjm** [comment]
You can close this PR if you wish. Especially as the Makefiles appear to be redundant.

**Pull request closed without merging**
